# Generated by Django 2.2.5 on 2019-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codeDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_code', models.TextField()),
                ('time_of_execution', models.DateTimeField(verbose_name='Time Executed')),
                ('count', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
