# Generated by Django 2.2.5 on 2019-09-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedb',
            name='time_of_execution',
            field=models.CharField(max_length=200),
        ),
    ]
